import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import { QueryProvider } from "@/providers/query.provider";

export const metadata: Metadata = {
    title: "Home - Canva",
    description: "Generated by create next app",
};

const font = Work_Sans({
    subsets : ["latin"],
    weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
              className={font.className}
            >
                <QueryProvider>
                    <Toaster position="top-right" />
                    {children}
                </QueryProvider>
            </body>
        </html>
    );
}
